### ISSUE TITLE
Have diverse staking success messages

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1134]
UI Version: 0.9.4

Description:

Staking success messages could be more useful. Rather than "bonding/unbonding successful". Would be cool to see "Bonding N steak to Validator X was successful" as example of more specific message.

Scope:
- Define diverse success messages for staking actions.
- Add the messages in code.

**Comment by jbibla** [comment]
@faboweb great suggestion.

i'd like to improve our notification design. let's discuss this too!

**Comment by NodeGuy** [comment]
Let's move this to Staking 2.0 so that we can complete Staking 1.0.

**Comment by faboweb** [comment]
I think improving the messages is not much work and a lot of benefit for our users.
The suggested improvements to notifications in general live in #891 and could imo be done later.

**Comment by NodeGuy** [comment]
OK, the notification suggestions are out of scope.  Do we still need to split this issue?

**Comment by fedekunze** [comment]
@faboweb Yeah, we can use the request error response msgs from the `sdk.Error` `ABCILog()` function. Although I've just realized that we're returning only type `error` msgs on LCD endpoints instead of the `sdk.Error`s (which have the nice JSON format errors that we want). 

So in summary, we are not getting the error msgs that we want to retrieve from the SDK...

**Comment by faboweb** [comment]
> So in summary, we are not getting the error msgs that we want to retrieve from the SDK...

Ref: https://github.com/cosmos/voyager/issues/1192

Summing up:
Errors will be displayed from the LCD. Success messages will be custom messages from Voyager. Then we don't need to split this. Any more input from our UX guy @jbibla ?

**Comment by jbibla** [comment]
i want to update the designs. in progress.

**Comment by NodeGuy** [comment]
The situation here is a bit confusing.  Am I understanding this correctly that the part of the SDK we're depending on for this feature isn't working properly?  If so, let's block this issue and halt work on it until the SDK is fixed and let's fix it ourselves if necessary.  Otherwise we're losing efficiency.

**Comment by faboweb** [comment]
No. This is about defining diverse success messages. Ref https://github.com/cosmos/voyager/issues/1134#issuecomment-418062900

**Comment by NodeGuy** [comment]
Oh, I see.  The error messages are being handled by https://github.com/cosmos/voyager/issues/1192.

**Comment by NodeGuy** [comment]
Please remove issues from the backlog when moving them into Scrumptious.
