### ISSUE TITLE
Validator coloring thresholds

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1336]
We need to decide which thresholds we want to use for the validator warnings:

![image](https://user-images.githubusercontent.com/5869273/45814614-6fd42f00-bcd6-11e8-8a90-f25837794bdf.png)

Pulling in @gamarin2 @cwgoes @rigelrozanski 

Scope:
- [ ] decide on thresholds
- [ ] implement thresholds

**Comment by faboweb** [comment]
> Slashes: First we need to define how many slashes one gets for each fault. Double signing should probably count as 20 or 30 slashes if 1 slash is given for 1 downtime penalty.

I like the idea. How about just adding up slashed percent: `0.01%  + 0.1% + 5% = 5.11%`

> Commission: I'm still skeptical that we need colours for this one. It really depends on so many factors like Atom price, etc.

But those factors go for everybody. I don't really get your hesitation. Could you maybe try to convince me a little more? :)

**Comment by gamarin2** [comment]
> But those factors go for everybody. I don't really get your hesitation. Could you maybe try to convince me a little more? :)

How do you objectively determine if a commission is too high? You can't put absolute numbers, cause imagine Atom price tanks so hard that all validators have to substantially increase their commissions. Everybody would be in red. 

So then you have the option of looking at the median commission or something like that, and then put in red validators that deviate from the median from +20%? +30%? It's too arbitrary for me.  But if we do decide to go with colors for commission, then I think it should be based on a median mechanism

**Comment by faboweb** [comment]
I get it now. Thank you. I like the median idea. Let's go with your proposal and not color it in the first iteration.

**Comment by cwgoes** [comment]
I like the median idea too, and it might apply to more than just commission - delegators are always choosing between a set of real validators, why not base our UI indicators on how those validators are actually performing instead of hardcoded thresholds? In any case, for all stats, could we show on hover the percent deviation (up or down) from the median commission?

I think uptime duration and percentage are both important. Duration maybe doesn't require a color - and I don't think we want to treat "low" durations as bad - but it's definitely an important characteristic in a delegator choosing whether or not to put their funds at risk.

I'm not too opinionated on how exactly we count slashes; I think it's more important to link to the specific events in question (and maybe give the validator a chance to explain the situation - what if Tendermint had a bug?). Maybe a simple "has ever been slashed" green/red box would do.

**Comment by fedekunze** [comment]
maybe we want to reconsider changing the priority for this? 
[Tweet Forbole](https://twitter.com/terencesflam/status/1106298432866541568)
[Tweet Melea](https://twitter.com/cryptoMelea/status/1106241443536998400)

**Comment by jackzampolin** [comment]
What needs to be done to implement here?

**Comment by jbibla** [comment]
it's quite easy on our end. nothing needed from the SDK, aside from some insight and guidance on how determine reasonable thresholds. 

when does a validator turn from green to red?

not high priority but would be cool to hear thoughts from others if they have feelings on this subject.

**Comment by jackzampolin** [comment]
@jbibla can you produce some numbers you think are good and then we can go with/discuss those?
