### ISSUE TITLE
Configurable Lunie

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1951]
Idea:
The Voyager code (bundle after Webpack magic) should be completely independent from the hard coded config values like timeouts and backend endpoints. The values should life in a `config.json` which is loaded independently from the Voyager bundle. This enables us or other people deploying Voyager to quickly change those settings without touching the bundle. This enables i.e. deploying the same bundle in different scenarios.

Loading the `config.json` async could slow down the loading process of the application. In this case, the server could render the `config.json` into the `index.html` on load. But this might not be necessary.

**Comment by sabau** [comment]
`STARGATE=<myaddress> build:ui`

**Comment by sabau** [comment]
@cosmos/sre what do you think about this?
Basically the two options are:
- build a version with the bundled configuration beforehand (you can customise with ENV variables at build time)
- building a version that read an external static config.json file and you can change manually to update the behaviour

**Comment by marbar3778** [comment]
If you want to dynamically inject env variables then something like this could be done [abcinfinity/explorer](https://github.com/abcInfinity/Explorer/blob/master/client/server/index.js) and it serves the build files, I'm not sure if you guys are serving via a mini server or just serving the build file via nginx or something similar on the server. I haven't noticed any slow down for this approach in previous apps. If you would like to do the server I can take an approach and propose it.

Idea: instead of making it a singular wallet and UI you can create a simpler server with roughly three routes that add rpc & lcd ports and the wallet can have a tabbed to switch chains without having to worry about the config.json, or the config.json has the default chain ie. the cosmos hub chain.

**Comment by faboweb** [comment]
Upvoting. Building for multiple networks is not feasible imo. it's just easier to build once and deploy to multiple buckets with configs present. How those configs are served is open.

**Comment by jbibla** [comment]
@faboweb how do you propose we manage this? different master branches that match subdomains?

**Comment by faboweb** [comment]
I propose as above that we have a `config.json` with all properties necessary (rpc, stargate, chain-id and others). The actual website loads that file per chain. So the "binaries" are independent from the configuration. This allows to ship the "binaries" once and use them on different routes that serve different default `config.json` (as @marbar3778) proposed (this is a little more complex as you need a webserver that handles those routes and assignes default configs). Need to change a stargate URL? just change the value in the `config.json` on the S3 bucket, no rebuild required.

**Comment by jbibla** [comment]
@faboweb still relevant?

**Comment by jbibla** [comment]
@faboweb still relevant?

**Comment by faboweb** [comment]
Not relevant anymore.
