### ISSUE TITLE
E2E tests with Hasura backend

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2930]
We need to test Lunie end 2 end. Lunies stack now includes a backend. We need to also test this backend. When we start a testnet the backend needs to be filled with the testnet data.

AC:
- docker compose with Hasura and the testnet and the data crawler filling Hasura
- working delegation e2e tests

**Comment by faboweb** [comment]
Still working on it.

**Comment by the-phoenix** [comment]
@faboweb Hello 
Any updates with this issue? 
We're trying to run lunie server on our hosting server but can't get it running because of no information about Hasura Server. 
Can you provide us the Hasura Server info that you're using? or any database schema skeleton or minimum data needed to run this server.
