### ISSUE TITLE
hide tooltips on mobile

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3115]
**Is your feature request related to a problem? Please describe.**

- the tooltips don't display nicely on mobile. would be best to not use them in the native apps.

**Describe the solution you'd like**

- disable them / don't allow them to render based on `MOBILE_APP` flag

**Describe alternatives you've considered**

- perhaps there is some way they won't even be loaded (not just hidden)

**Additional context**

**Comment by mariopino** [comment]
By now implemented using the easy way.

Most optimal solution could be to not  import `vue-directive-tooltip` (and then don't use it with `Vue.use`) based on MOBILE_APP environment variable value.

Buut I think it is difficult to implement that way since tooltips are inline in the html of components using `v-tooltip` directive.

That would require to move all the tooltips from the components (content and other attributes like placement ... etc) to custom data directives (like data-tooltip, data-tooltip-placement... etc) and then implement a custom tooltip library to use that data attributes to render the tooltips.

Given that then we can conditionally import our tooltip library based on  the value of MOBILE_APP environment variable.
