### ISSUE TITLE
Clicking on Active on Validators page select both All and Active tabs

### ISSUE THREAD

**Issue by iambeone** [luniehq/lunie#3280]
Clicking on Active on Validators page select both All and Active tabs
![ezgif-1-348c75e76012](https://user-images.githubusercontent.com/9531274/70540754-9e625200-1b87-11ea-9ed5-eee757487ad1.gif)

**Comment by jbibla** [comment]
is this a css bug?

**Comment by iambeone** [comment]
Should be

**Comment by mariopino** [comment]
@iambeone I can't replicate it, what browser are you using?

**Comment by jbibla** [comment]
ah ok. this can be replicated by clicking on the tab that's already selected. it toggles the selected tab and then you are left "hovering" over the one that is now deselected, while the other is selected. 

the fix is just to make sure that when you click one side it only activates the side that was clicked.  right now both are toggles for each other.
