### ISSUE TITLE
Address not loading on Address Restore/Import (note: remove weird empty Javascript Object)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3927]
Kusama final battle!

**Comment by mariopino** [comment]
I tested it with 12 and 24 words seeds and this is working currently, so I think including a loading icon to replace the ugly `{}` should be enought.

**Comment by Bitcoinera** [comment]
Why taking so long on mobile though? Doesn't make sense right?

But yeah, let's just add the loading thing for now. I can do that

**Comment by Bitcoinera** [comment]
Well, I think we can review & merge your PR for now and focus on subscription VS polling and re-check on mobile. See if that fixes it

**Comment by mariopino** [comment]
> Why taking so long on mobile though? Doesn't make sense right?

Sadly yes, things I learned from that:

1. As you would expect addresses with 24 word seeds takes longer to generate than 12 word seeds ones.
2. In Polkadot you can not test a random seed phrase, I don't know what the constraints are in effect but if you in example make a typo writing your seed, you'll end probably with and eternal spinner and this error in console:

```
RuntimeError: unreachable
    at wasm-function[192]:0x2190d
    at wasm-function[480]:0x29a54
    at wasm-function[573]:0x2ace1
    at wasm-function[296]:0x2598d
    at wasm-function[363]:0x2751e
    at wasm-function[26]:0xdbdd
    at wasm-function[332]:0x26860
    at module.exports.ext_bip39_to_mini_secret (webpack-internal:///./node_modules/@polkadot/wasm-crypto/wasm.js:535:14)
    at eval (webpack-internal:///./node_modules/@polkadot/wasm-crypto/exports.js:15:14)
    at toMiniSecret (webpack-internal:///./node_modules/@polkadot/util-crypto/mnemonic/toMiniSecret.js:25:46)
```

BTW: This can be a common issue and I think we should handle it and show a error message to the user. This is very easy and can be done in this PR: just put `getAddressFromSeed` in a try/catch block to capture the error and display an error message instead of address )

**Comment by Bitcoinera** [comment]
> 2. In Polkadot you can not test a random seed phrase, I don't know what the constraints are in effect but if you in example make a typo writing your seed, you'll end probably with and eternal spinner and this error in console:

I still don't see why in mobile it behaved differently and also don't get the typo thing. If you make a typo, you will simply get a wrong address, or not? Otherwise we should know which those constraints are to add them to our validations

**Comment by Bitcoinera** [comment]
We will need to check this on the new mobile release though 👀
