### ISSUE TITLE
User unable to claim Kava rewards and pay with claimed amount

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4323]
**Describe the bug**
User does not have enough available balance to pay for a claim transaction. Wants the fees deducted from their claimed rewards balance instead. Says it was available in Kava-2 and does not work on Kava-3 now
 
@Bitcoinera any thoughts?

![photo_2020-06-20 14 46 31](https://user-images.githubusercontent.com/1614127/85209322-f59a6980-b304-11ea-81b7-70c3d230fce6.jpeg)

![photo_2020-06-20 14 46 36](https://user-images.githubusercontent.com/1614127/85209325-f92df080-b304-11ea-9541-b87710deed69.jpeg)

**Comment by Bitcoinera** [comment]
Yes, this is actually the way it is supposed to work specifically for Kava and e-Money. Fees cannot be deducted on this networks. I mean, I will try again to see if they changed it in the new version, but before it was impossible.

And I think what this user remembers is that we didn't block them before on this step, but if we do now it is for a good reason (transaction cannot even be broadcasted without the needed fees)

**Comment by Bitcoinera** [comment]
As I expected, I tried sending a transaction on Kava-3 without any fee and got this error before even being able to broadcast:

<img width="440px"  src="https://user-images.githubusercontent.com/40721795/85223193-22ac5200-b3c1-11ea-9ebd-6d68d6da99c8.png">

So the user cannot really perform this action without having funds. If they are upset about this, they should contact the Kava team or the validators, since they might be able to change this behavior by changing their nodes configuration

**Comment by Bitcoinera** [comment]
In any case, we display warning messages in both Send and Stake transactions so users are aware it is a bad idea to go completely dry on funds. If they don't pay attention to this we can do nothing. This is not a bug
