### ISSUE TITLE
Change the way we release (Change request)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5072]
During the time @faboweb was out due to _force majeure_ Jordan and I discovered that the release process is somehow overcomplicated and somehow unpredictable.

Being develop the base branch for the Simsala branches, you never know for certain if it will then successfully merge to master after merging the Simsala PR, because it is not possible to see the conflicts.

Another issue with the current release process is that there too many steps:

We need to push to release (1) to open the Simsala branches (2), to merge these to develop (3) to then finally merge develop to master (4) and then (only if CHANGELOG.md changed) finally in fact release. This seems overcomplicated. It seems more reasonable to work with PRs from develop to master and then manually increment the version and CHANGELOG.md. I am not sure if this is the only thing Simsala actually does. Or another option would be to just work with release, develop and master. When doing `yarn release` in develop, the `release` branch opens a PR with base master and in that PR we automatically increment the version number & modify CHANGELOG.md.

In another PR (#5020), I also proposed staying the same but adding a merge strategy from develop to master so conflicts don't spoil our release process and we don't need to always make sure if something got released or not.

In any case, our release process seems quite cumbersome and is really taking us so much time, unfortunately

**Comment by jbibla** [comment]
strongly agree with ana here! 

some other thoughts: having to constantly check the workflow files is a sign that the process is not implicit enough. i think it would be best if workflows were only triggered by human actions. our whole release flow is predicated on the changelog (which i still think nobody actually checks / reads / uses) instead of prioritizing predictability and developer ease of use.

the work that simsala does would be better as part of the action flow - we should check to see if there are existing github actions that can increment versions and manage changelogs for us. 

```
merge any changes on develop -> triggers a deploy on staging
merge any changes on master -> github action / checks for whatever we need -> triggers a deploy to production
```

if we simplify this process we can also reduce the number of checks and confusing red x's on various steps of our flow. all checks should be green before we merge!!

**Comment by faboweb** [comment]
Requirments:
- Hot fixes: We need to fix master in some cases immediately
- Version Control: Especially in the future when we offer a Lunie to devs, we need to be rigid here
- Deploy: We need to be able to deploy to staging and production instances

Problems:
- the merge to master fails because there are hot fixes there that don't merge easily back to our new release. mainly the CHANGELOG.md as they need to be edited on any hot fix and release to show that a module was updated so we don't deploy all modules all the time

Solution:
- do releases to master manually right now: checkout the released commit, merge master -> push to master

**Comment by jbibla** [comment]
i agree with the requirements list Fabo! 

i would like to see a release flow where we can trigger a release PR from each subrepo that doesn't check the changes / changelog file but just the folder for any changes. 

i think the CI should be able to tag and increment the version for us accordingly. ideally these should end up here: https://github.com/luniehq/lunie/releases with human readable changes listed.

**Comment by faboweb** [comment]
> i would like to see a release flow where we can trigger a release PR from each subrepo that doesn't check the changes / changelog file but just the folder for any changes.

we can't do that. only a point in time for a module that we consider release worthy can be published. as we merge all modules also the ones in development state to master. that is why we check for an update to the CHANGELOG.md

**Comment by faboweb** [comment]
> i think the CI should be able to tag and increment the version for us accordingly. ideally these should end up here: https://github.com/luniehq/lunie/releases with human readable changes listed.

great feature addition for Simsala and not that complicated

**Comment by Bitcoinera** [comment]
This is moving forward! :woman_dancing: 

> do releases to master manually right now: checkout the released commit, merge master -> push to master

Okay :ok_hand:

**Comment by jbibla** [comment]
> we can't do that. only a point in time for a module that we consider release worthy can be published. as we merge all modules also the ones in development state to master. that is why we check for an update to the CHANGELOG.md

i don't understand what this means.
